# Generated by Django 3.0.7 on 2020-07-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Group's name")),
                ('description', models.TextField(verbose_name='Additional group description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp when group was created')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Link to the source (video / article / ...)')),
                ('description', models.TextField(verbose_name='Description about link')),
                ('is_done', models.BooleanField(default=False, verbose_name="Flag that indicates whether user's finished processing source by link")),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp when link was added')),
                ('groups', models.ManyToManyField(related_name='links', to='groups.Group', verbose_name='Many to many relationship with group')),
            ],
            options={
                'db_table': 'links',
            },
        ),
    ]
