# Generated by Django 3.0.7 on 2020-07-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20200728_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description about link'),
        ),
    ]
