# Generated by Django 3.0.7 on 2020-08-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20200803_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='groups',
        ),
        migrations.AddField(
            model_name='link',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='groups.Group', verbose_name="Link's group"),
            preserve_default=False,
        ),
    ]
